### ISSUE TITLE
How did you use unlabeled dataset?

### ISSUE THREAD

**Issue by dXDb** [kakaobrain/scrl#9]
Paper  p. 12
Table A3. COCO detection using Faster R-CNN, ResNet-50-FPN.Upstreams are trained with the unlabeled COCO dataset with 2000epochs.

In your code, it have to use labels like classification task, but in the paper, you described you used unlabeled COCO dataset.
Doesn't it care about labels? Then, can I use like this?

data/mydataset/0/image_0.jpg
data/mydataset/0/image_1.jpg
data/mydataset/0/...
data/mydataset/1/image_0.jpg
data/mydataset/1/image_1.jpg
data/mydataset/1/...

(I changed imageNet to imageFolder.)

**Comment by prayforher** [comment]
SCRL doesn't need labels to train a model since it is a self-supervised learning method.

I think you probably found an online evaluation block that uses labels. We've implemented a code to evaluate the model's linear evaluation result on the fly. It means if you disable the online evaluation mode, you don't need labels to train a model.

Even though you enable the online evaluation mode, the loss from the online evaluation block is detached. It means it does not affect the model training.

**Comment by dXDb** [comment]
답변 감사합니다 :)

I thought this method was using an unlabeled dataset. But looking at the 88 line of the trainer.py, it needs labels. So I misunderstood. But after watching your answer, I saw the 234 line part of trainer.py, the label will only be used for the evaluation part. From now on, I will read the code in more detail. Thank u 👍
